POST http://localhost:5000/api/users/register HTTP/1.1
content-type: application/json

{
    "name": "Goyo",
    "email": "goyo@gmail.com",
    "password":"12345",
    "lastname": "grilo"
}    
/*

    password: {           
        type: String,
        minglength: 5
    },
    lastname: {
        type:String,
        maxlength: 50
    },
    role : {
        type:Number,
        default: 0 
    },
    image: String,
    token : {
        type: String,
    },
    tokenExp :{
        type: Number
    }
  */  